// <auto-generated />
using System;
using ClothingStoreV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
#nullable disable
namespace ClothingStoreV2.Migrations
{
    [DbContext(typeof(ClothingStoreContext))]
    partial class ClothingStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("ClothingStoreV2.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("CategoryLabel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");
                    b.Property<byte?>("TargetGender")
                        .HasColumnType("smallint");
                    b.HasKey("Id");
                    b.ToTable("Categories");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");
                    b.Property<string>("ItemLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");
                    b.Property<string>("PhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");
                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,0)");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.ToTable("Items");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<bool?>("InProgress")
                        .HasColumnType("boolean");
                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");
                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric(18,0)");
                    b.Property<int?>("UserId")
                        .HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("Purchases");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.PurchaseItem", b =>
                {
                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");
                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,0)");
                    b.Property<short?>("Quantity")
                        .HasColumnType("smallint");
                    b.HasKey("PurchaseId", "ItemId")
                        .HasName("PK__Purchase__CC2D838651A53020");
                    b.HasIndex("ItemId");
                    b.ToTable("PurchaseItems");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.UserDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Address1")
                        .HasMaxLength(95)
                        .HasColumnType("character varying(95)");
                    b.Property<string>("Address2")
                        .HasMaxLength(95)
                        .HasColumnType("character varying(95)");
                    b.Property<int?>("Age")
                        .HasColumnType("integer");
                    b.Property<string>("City")
                        .HasMaxLength(189)
                        .HasColumnType("character varying(189)");
                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");
                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");
                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");
                    b.Property<string>("IdentityId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");
                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");
                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");
                    b.Property<string>("ZipCode")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");
                    b.HasKey("Id");
                    b.ToTable("UserData");
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");
                    b.ToTable("AspNetRoles", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType")
                        .HasColumnType("text");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");
                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetRoleClaims", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");
                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");
                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");
                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");
                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");
                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");
                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");
                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");
                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");
                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");
                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");
                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");
                    b.ToTable("AspNetUsers", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ClaimType")
                        .HasColumnType("text");
                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserClaims", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");
                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");
                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");
                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");
                    b.HasKey("LoginProvider", "ProviderKey");
                    b.HasIndex("UserId");
                    b.ToTable("AspNetUserLogins", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");
                    b.Property<string>("RoleId")
                        .HasColumnType("text");
                    b.HasKey("UserId", "RoleId");
                    b.HasIndex("RoleId");
                    b.ToTable("AspNetUserRoles", (string)null);
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");
                    b.Property<string>("Name")
                        .HasColumnType("text");
                    b.Property<string>("Value")
                        .HasColumnType("text");
                    b.HasKey("UserId", "LoginProvider", "Name");
                    b.ToTable("AspNetUserTokens", (string)null);
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Item", b =>
                {
                    b.HasOne("ClothingStoreV2.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Items__CategoryI__286302EC");
                    b.Navigation("Category");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Purchase", b =>
                {
                    b.HasOne("ClothingStoreV2.Models.UserDatum", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Purchases__UserI__2B3F6F97");
                    b.Navigation("User");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.PurchaseItem", b =>
                {
                    b.HasOne("ClothingStoreV2.Models.Item", "Item")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseI__ItemI__2F10007B");
                    b.HasOne("ClothingStoreV2.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseI__Purch__2E1BDC42");
                    b.Navigation("Item");
                    b.Navigation("Purchase");
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Category", b =>
                {
                    b.Navigation("Items");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Item", b =>
                {
                    b.Navigation("PurchaseItems");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });
            modelBuilder.Entity("ClothingStoreV2.Models.UserDatum", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
